### ISSUE TITLE
non standard LOOP - can not be build with ECL

### ISSUE THREAD

**Issue by avodonosov** [akapav/js#13]
LOOPs like this
```common-lisp
  (loop :for obj := start :then (cls-prototype cls) :while obj
        :for cls := (obj-cls obj) :for vals := (obj-vals obj) :do
```
are non standard - :for can not follow :while. 

Most Lisps tolerate this, but not ECL:
http://comments.gmane.org/gmane.lisp.ecl.general/3344

**Comment by marijnh** [comment]
Going to assume this is no longer a problem in current ECL.
