### ISSUE TITLE
Fails to eval ammo.js (bullet library from emscripten)

### ISSUE THREAD

**Issue by BradWBeer** [akapav/js#29]
It breaks after a "while(0);while(1)" statement, it's optimized javascript so it's a little hard to find. Line 19, column 58322.

**Comment by marijnh** [comment]
The issue could be reduced to this nested do/while loop:

    do do {} while(0); while(0);

Which `parse-js` wasn't handling because it didn't expect semicolons after a do/while loop. Attached patch fixes this.

**Comment by BradWBeer** [comment]
What Implementation did you eval ammo.js with? SBCL keeps crashing with the error: "Process inferior-lisp killed". Any ideas?

**Comment by marijnh** [comment]
I didn't eval ammo.js, I only fixed the parse error it produced.

I suspect that trying to run AMD.js soup is more than this library can handle. It is a hobby-project by two people, and hasn't seen serious work for years (and probably won't see serious work by the original authors at all anymore).
