### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by vtomole** [akapav/js#32]
When I run: (asdf:oos 'asdf:load-op :cl-js), I get a:There is no class named CL-JS::DOBJ error.
This is the full error:http://pastebin.com/3K9eAMBP

**Comment by marijnh** [comment]
That trace seems to be from loading a .fasl file. Have you tried deleting those and reloading? The error is strange, since `dobj` is defined in a struct in the very file that's causing the error.

**Comment by vtomole** [comment]
I cant find this .fasl file, is it in the js repository?

**Comment by marijnh** [comment]
.fasl files are used by implementations like SBCL to store and quickly reload compiled code, so they are not in the repository, but they will be on your disk after you've loaded the library

**Comment by vtomole** [comment]
I installed a new os and it works now. Thank you!
