### ISSUE TITLE
Wrong date milliseconds value

### ISSUE THREAD

**Issue by hazon** [akapav/js#33]
Hi,
    it seems to me that the way milliseconds are being calculated in a date is wrong.

The local function `date-milliseconds` (in *runtime.lisp* at line 818) should be defined as:

```
 (date-milliseconds (timestamp)
           (let ((start-day #.(local-time:day-of (local-time:encode-timestamp 0 0 0 0 1 1 1970 :timezone local-time:+utc-zone+))))
             (+ (* #.(* 1000 3600 24) (- (local-time:day-of timestamp) start-day))
                (* 1000 (local-time:sec-of timestamp))
                (truncate (local-time:nsec-of timestamp) 1000000))))
         (date-from-milliseconds (ms)
```

I've just changed the line `(mod (local-time:nsec-of timestamp) 1000000)` changing `mod` to `truncate`.
Because the number of nano-seconds should be divided by 1000000 to obtain milliseconds (instead of using the remainder value).

**Comment by marijnh** [comment]
I think you're right. See attached patch.
